### ISSUE TITLE
gulp.watch 无法触发build任务

### ISSUE THREAD

**Issue by pcdelphi** [happypeter/flex#2]
gulpfile.js文件中用 `gulp.watch(['**/*.html'], ['build']);`，无论怎么修改html文件，都无法触发build，但是改成·gulp.watch(['layout/_.html', 'pages/_.html'], ['build']);·，则可以触发build，请问是怎么回事？

**Comment by happypeter** [comment]
嗯，的确奇怪，应该是可以的，因为咱们代码中的这一行：https://github.com/happypeter/flex/blob/gh-pages/source/gulpfile.js#L46

其中就会包括 `layout/*.html` 。

**Comment by happypeter** [comment]
把您的代码上传一下吧，我看看。

**Comment by pcdelphi** [comment]
代码已经上传到`https://github.com/pcdelphi/flex/tree/9ad9305ec3aa57aee13f316909d5cec364b9db0f`
刚才又测试了一下，如果使用`**/*.html`，gulp会停在`Starting 'watch' ...`这一步。
如果分别列出目录的话，watch任务会Finished，然后接着完成default任务。

**Comment by happypeter** [comment]
运行了一下您的代码，发现在我的机器上，执行 `gulp` 命令，会出现下面的错误

```
Unhandled rejection TypeError: tmpl is not a function
    at /Users/peter/tmp/his-flex/source/node_modules/consolidate/lib/consolidate.js:779:16
    at /Users/peter/tmp/his-flex/source/node_modules/consolidate/lib/consolidate.js:143:5
    at Promise._execute (/Users/peter/tmp/his-flex/source/node_modules/bluebird/js/relea
```

而运行我的 https://github.com/happypeter/flex 则一切正常。

具体这个错误的原因我也没有 google 到，这个也很正常，很多错误的报错信息跟错误出现的地方可能根本看不出任何关系。

所以也不必每个错误都深究。解决问题，按照正确的方式去操作就可以了。

所以，具体的做法可以这样：
- clone 正确的代码下来，逐渐删除正确的代码的各项功能
- 直到功能跟您目前想要达成的功能相近了
- 过程中不断测试，确保代码运行一切正常
- 最后，对比一下正常的代码和您的错误代码的差异就知道问题出在哪里了。

调试，调试，调完再试，很多时候具体工作中就是用这种笨办法解决问题的，要逐步适应起来。

**Comment by pcdelphi** [comment]
好的。谢谢peter老师
